export const powerWater = [
  {
    Serial: 1,
    "Project name": "Tihama Power Generation Company Ltd (Saudi Arabia)",
    "Project Capacity": "1063 MW",
    "Debt Raised": "USD 344 Mn (80:20 D/E for project cost of USD 430 Mn)",
  },
  {
    Serial: 2,
    "Project name": "Sohar Power Company (Oman)",
    "Project Capacity": "585 MW; 33 MIGD",
    "Debt Raised": "USD 517.5 Mn",
  },
  {
    Serial: 3,
    "Project name": "Q Power QSC (Qatar)",
    "Project Capacity": "1025 MW; 60 MIGD",
    "Debt Raised": "USD 720 Mn (80:20 D/E for project cost of USD 900 Mn)",
  },
  {
    Serial: 4,
    "Project name": "Taweelah Asia Power Company (UAE)",
    "Project Capacity": "1928 MW; 157 MIGD",
    "Debt Raised": "USD 1,150 Mn",
  },
  {
    Serial: 5,
    "Project name": "Shuaibah Water and Electricity Company (Saudi Arabia)",
    "Project Capacity": "900 MW; 194 MIGD",
    "Debt Raised": "USD 1.5 Bn",
  },
  {
    Serial: 6,
    "Project name": "Hidd Power Company (Bahrain)",
    "Project Capacity": "910 MW; 90 MIGD",
    "Debt Raised": "USD 1.06 Bn ((85:15 D/E for project cost of USD 1.25 Bn)",
  },
  {
    Serial: 7,
    "Project name": "Emirates Sembcorp Water and Power Company P.J.S.C (UAE)",
    "Project Capacity": "760 MW; 100 MIGD",
    "Debt Raised": "USD I,726 Mn",
  },
  {
    Serial: 8,
    "Project name": "Gulf Total Tractebel Power Company (UAE)",
    "Project Capacity": "1592 MW; 84 MIGD",
    "Debt Raised": "USD 1.102 Bn",
  },
  {
    Serial: 9,
    "Project name": "Shuqaiq Water and Electricity Company (Saudi Arabia)",
    "Project Capacity": "850 MW; 47 MIGD",
    "Debt Raised": "USD 1,830 Bn",
  },
  {
    Serial: 10,
    "Project name": "SMN Barka Power Company S.A.O.C (Oman)",
    "Project Capacity": "678 MW; 26.4MIGD",
    "Debt Raised": "USD 800 Mn",
  },
  {
    Serial: 11,
    "Project name": "Jubail Water and Power Company (Saudi Arabia)",
    "Project Capacity": "2,750 MW; 177 MIGD",
    "Debt Raised":
      "Term Loan-USD 100 Mn, & Revolving Loan-USD 110 Mn with Standard Chartered",
  },
  {
    Serial: 12,
    "Project name": "Mesaieed Power Company Limited (Qatar)",
    "Project Capacity": "2000 MW",
    "Debt Raised": "USD 2.05 Bn",
  },
  {
    Serial: 13,
    "Project name": "Fujairah Asia Power Company P.J.S.C (UAE)",
    "Project Capacity": "2000 MW; 130 MIGD",
    "Debt Raised": "USD 2.8 Bn",
  },
  {
    Serial: 14,
    "Project name": "Qatar Electricity and Water Company Q.S.C (Qatar)",
    "Project Capacity": "45 MIGD",
    "Debt Raised": "USD 1,575 Mn (75:25 D/E for project cost of USD 2.1 Bn)",
  },
  {
    Serial: 15,
    "Project name": "Port Said East Power S.A.E (Egypt)",
    "Project Capacity": "680 MW",
    "Debt Raised":
      "Acquisition financing, comprising USD 150 Mn non-recourse loan, & USD 162 Mn replacement credit support facilities-for both projects, No. 15. & 16.",
  },
  {
    Serial: 16,
    "Project name": "Suez Gulf Power S.A.E (Egypt)",
    "Project Capacity": "682 MW",
    "Debt Raised":
      "Acquisition financing, comprising USD 150 Mn non-recourse loan, & USD 162 Mn replacement credit support facilities-for both projects, No. 15. & 16.",
  },
  {
    Serial: 17,
    "Project name": "Ras Girtas Power Company (Qatar)",
    "Project Capacity": "2700 MW; 63 MIGD",
    "Debt Raised": "USD 3.25 Bn",
  },
  {
    Serial: 18,
    "Project name": "Sembcorp Salalah Power and Water Company S.A.O.C (Oman)",
    "Project Capacity": "445 MW, 15 MIGD",
    "Debt Raised": "USD 750 Mn",
  },
  {
    Serial: 19,
    "Project name": "Al Batinah Power Company S.A.O.C (Oman)",
    "Project Capacity": "745 MW",
    "Debt Raised": "USD 350 Mn",
  },
  {
    Serial: 20,
    "Project name": "Al Suwadi Power Company S.A.O.C (Oman)",
    "Project Capacity": "745 MW",
    "Debt Raised": "USD 680 Mn",
  },
  {
    Serial: 21,
    "Project name": "Dhuruma Electricity Company (Saudi Arabia)",
    "Project Capacity": "1700 MW",
    "Debt Raised": "USD 1518 Mn",
  },
  {
    Serial: 22,
    "Project name": "Phoenix Power Company S.A.O.C (Oman)",
    "Project Capacity": "2000 MW",
    "Debt Raised": "USD 697 Mn",
  },
  {
    Serial: 23,
    "Project name": "Hajr for Electricity Production Company (Saudi Arabia)",
    "Project Capacity": "2580 MW",
    "Debt Raised": "USD 2 Bn",
  },
  {
    Serial: 24,
    "Project name": "UCH Power Ltd (Pakistan)",
    "Project Capacity": "404 MW",
    "Debt Raised": "USD 360 Mn",
  },
  {
    Serial: 25,
    "Project name": "Jorf Lasfar Energy Company S.A, G.S.A (Morocco)",
    "Project Capacity": "700 MW",
    "Debt Raised": "USD 1.4 Bn",
  },
  {
    Serial: 26,
    "Project name": "Amman Asia Electric Power H.S.C (Jordan)",
    "Project Capacity": "570 MW",
    "Debt Raised": "USD 607 Mn",
  },
  {
    Serial: 27,
    "Project name":
      "Al Mourjan for Electricity Production Company (Saudi Arabia)",
    "Project Capacity": "2060 MW",
    "Debt Raised": "USD 1.6 Bn",
  },
  {
    Serial: 28,
    "Project name": "Shamal Az-Zour Al-Oula (Kuwait)",
    "Project Capacity": "1500 MW & 105 MIGD",
    "Debt Raised": "USD 1.43 Bn",
  },
  {
    Serial: 29,
    "Project name": "Safi Energy Company (Morocco)",
    "Project Capacity": "1386 MW",
    "Debt Raised": "USD 2.6 Bn",
  },
  {
    Serial: 30,
    "Project name": "DEWA MBR Solar -Phase IV",
    "Project Capacity": "950MW",
    "Debt Raised": "USD 4.3 Bn",
  },
  {
    Serial: 31,
    "Project name": "Shams Ma'an Solar PV IPP",
    "Project Capacity": "52.5MW",
    "Debt Raised":
      "Project finance loans totaling USD129 million, arranged by Mizuho Bank, Ltd. (MHBK) as lead arranger, with co–financing provided by the Japan Bank for International Cooperation and Standard Chartered Bank",
  },
  {
    Serial: 32,
    "Project name": "Al Dur II IWPP",
    "Project Capacity": "950MW",
    "Debt Raised":
      "USD 786 million debt raised for USD 1.1 Bn of total project Cost",
  },
  {
    Serial: 33,
    "Project name": "FEWA UAQ IWP",
    "Project Capacity": "150 MIGD",
    "Debt Raised": "USD 680 Mn",
  },
  {
    Serial: 34,
    "Project name": "FEWA 500MW Solar PV IPP",
    "Project Capacity": "500 MW",
    "Debt Raised": "USD 250 Mn",
  },
  {
    Serial: 35,
    "Project name": "Al Ghubrah-3 IWP and Barka-5 desalination project (Oman)",
    "Project Capacity": "190,000 m3/day and 150,000 m3/day",
    "Debt Raised": "USD 470 Mn",
  },
  {
    Serial: 36,
    "Project name": "Rabigh III IWP",
    "Project Capacity": "600,000 m3 / day",
    "Debt Raised": "USD 550 Mn",
  },
  {
    Serial: 37,
    "Project name": "Haya Water (Oman)",
    "Project Capacity": "Ongoing",
    "Debt Raised": "USD 90 Mn",
  },
  {
    Serial: 38,
    "Project name": "Barakah nuclear power plant (UAE)",
    "Project Capacity": "5,600MW",
    "Debt Raised": "USD 20 Bn",
  },
  {
    Serial: 39,
    "Project name": "Salalah Power & Water Company",
    "Project Capacity": "445 MW, 15 MIGD",
    "Debt Raised": "USD 750 Mn",
  },
  {
    Serial: 40,
    "Project name": "Refinancing for Ruwais Power Company (UAE)",
    "Project Capacity": "1,507MW and 100MIGD",
    "Debt Raised": "Refinanced with a 24 year 144 A/Reg S project bond",
  },
  {
    Serial: 41,
    "Project name": "Azura-Edo Open Cycle Gas Turbine (Nigeria)",
    "Project Capacity": "459MW",
    "Debt Raised": "USD 590 Mn",
  },
  {
    Serial: 42,
    "Project name": "Mesaieed Water and Power Project (Qatar)",
    "Project Capacity": "2000MW",
    "Debt Raised": "USD 1.35 Bn",
  },
  {
    Serial: 43,
    "Project name": "Ras Laffan B Power and Water (Qatar)",
    "Project Capacity": "2730MW and 63MIGD",
    "Debt Raised": "USD 720 Mn",
  },
  {
    Serial: 44,
    "Project name": "Rabigh Power and Water Project",
    "Project Capacity": "1,204 MW",
    "Debt Raised": "USD 1.83 Bn",
  },
  {
    Serial: 45,
    "Project name": "Al Dur Power and Water Project (Bahrain)",
    "Project Capacity": "220MW",
    "Debt Raised": "USD 1.2 Bn international tranche",
  },
  {
    Serial: 46,
    "Project name": "Shirsjgang 2-Combined Cycle Power Plant (Bangladesh)",
    "Project Capacity": "225 MW",
    "Debt Raised":
      "USD 44 Mn (MIGA-Non-Honoring of Sovereign Financial Obligation guarantee)",
  },
  {
    Serial: 47,
    "Project name": "Jhajjar plant-CLP India",
    "Project Capacity": "1320 MW",
    "Debt Raised": "USD 288 Mn",
  },
];

export const nonPowerWater = [
  {
    Serial: 1,
    "Project name": "Guangdong regasification Project (China)",
    "Project Capacity": "Project Capacity: 6.8 Mn Tonnes",
    "Debt Raised": "USD 657 Million",
  },
  {
    Serial: 2,
    "Project name": "PetroNet LNG (India)",
    "Project Capacity": "NA",
    "Debt Raised": "Two Bond Issues, ~$115 Mn Each, & $70 Mn loan guarantee",
  },
  {
    Serial: 3,
    "Project name": "Istanbul Tunnel (Eurasia Tunnel)-Roads Project",
    "Project Capacity": "Roads Project",
    "Debt Raised": "USD 1.05 Bn",
  },
  {
    Serial: 4,
    "Project name": "Transformative Waste-to-Energy Project (UAE)",
    "Project Capacity": "5000 Metric tonnes to 185 MW",
    "Debt Raised": "USD 700 Mn",
  },
  {
    Serial: 5,
    "Project name": "DP World's ports in Djibouti",
    "Project Capacity": "Project Capacity: 550k TEUs",
    "Debt Raised": "USD 396 Mn",
  },
  {
    Serial: 6,
    "Project name": "DP World's ports in Senegal",
    "Project Capacity": "Project Capacity: 550k TEUs",
    "Debt Raised": "USD 14 Mn",
  },
  {
    Serial: 7,
    "Project name": "Oyu Tolgoi Project (Mongolia)",
    "Project Capacity": "Mining Project",
    "Debt Raised": "USD 4.4 Bn",
  },
  {
    Serial: 8,
    "Project name": "Oman refineries",
    "Project Capacity": "Project Capacity: 222K BPD",
    "Debt Raised": "USD 1,370 Mn",
  },
  {
    Serial: 9,
    "Project name": "Ma’aden Phosphate Fertilizer Project (Saudi Arabia)",
    "Project Capacity": "16 million tonnes/year",
    "Debt Raised": "USD 3.86 Bn",
  },
  {
    Serial: 10,
    "Project name": "Victoria Terminal AUS",
    "Project Capacity": "Project Capacity: 1.8 mn TEUs",
    "Debt Raised": "USD 285 Mn",
  },
  {
    Serial: 11,
    "Project name": "Corpus Christi Liquefaction Project",
    "Project Capacity": "10Mtpa LNG storage",
    "Debt Raised": "USD 11.5 Bn",
  },
];
